### ISSUE TITLE
Error finding skim config

### ISSUE THREAD

**Issue by pkausw** [kandrosov/RunKit#10]
Dear maintainers,

I'm part of the HH->bbtautau team at the university of Hamburg, where we've been producing custom nanoAOD files using your (very nice!) tool for quite a while now. Yesterday, I tried updating our setup to the latest version in this repository using the `main` branch. I'm running the code on one of the lxplus8 machines (same as before) with the same software setup (CMSSW_13_0_7). Executing the command

```bash
python RunKit/crabOverseer.py --cfg NanoProd/crab/overseer_cfg_uhh.yaml --update-cfg --no-loop --work-area resubmit_01-11-2023 NanoProd/crab/Run2_2018_uhh/resubmit_data2.yaml
```

generates the following output

<details>
<summary> Local shell output </summary>

```bash
[2023-11-01 15:20:47] Updating...
EGamma_Run2018D: submitting ...
Importing CMSSW configuration RunKit/nanoProdWrapper.py
Traceback (most recent call last):
  File "/afs/cern.ch/user/p/pkeicher/workdir/public/NanoProd/RunKit/crabSubmit.py", line 74, in <module>
    submit(task)
  File "/afs/cern.ch/user/p/pkeicher/workdir/public/NanoProd/RunKit/crabSubmit.py", line 68, in submit
    crabCommand('submit', config=config, dryrun=task.dryrun)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABAPI/RawCommand.py", line 28, in crabCommand
    return execRaw(command, arguments)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABAPI/RawCommand.py", line 48, in execRaw
    res = cmdobj()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/submit.py", line 107, in __call__
    dummy_inputfiles, jobconfig = plugjobtype.run(filecacheurl)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/JobType/Analysis.py", line 87, in run
    self.cmsswCfg = CMSSWConfig(config=self.config, logger=self.logger,
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/JobType/CMSSWConfig.py", line 87, in __init__
    self.fullConfig = imp.load_module(cfgBaseName, configFile, pathname, description)
  File "/cvmfs/cms.cern.ch/el8_amd64_gcc11/external/python3/3.9.14-76a14295dd5255228210eb596893b98c/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/el8_amd64_gcc11/external/python3/3.9.14-76a14295dd5255228210eb596893b98c/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/afs/cern.ch/work/p/pkeicher/public/NanoProd/RunKit/nanoProdWrapper.py", line 93, in <module>
    with open(options.skimCfg, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'skim_uhh.yaml'

```
</details>

I tried changing the path to the skim config in `overseer_cfg_uhh.yaml`, which solved this issue and submitted the jobs. However, all crab jobs fail with error code `666`. This is an example from one of the job logs:

<details>
<summary> crab job log </summary>

```bash
== CMSSW: Begin processing the 56501st record. Run 322407, Event 310276462, LumiSection 206 on stream 0 at 02-Nov-2023 09:25:45.410 CET
== CMSSW: Begin processing the 56601st record. Run 322407, Event 309001001, LumiSection 206 on stream 0 at 02-Nov-2023 09:26:19.744 CET
== CMSSW: Begin processing the 56701st record. Run 322407, Event 309905451, LumiSection 206 on stream 0 at 02-Nov-2023 09:26:53.415 CET
== CMSSW: Begin processing the 56801st record. Run 322407, Event 309610004, LumiSection 206 on stream 0 at 02-Nov-2023 09:27:36.792 CET
== CMSSW: 02-Nov-2023 09:27:42 CET  Closed file file:input_9207.root
== CMSSW: >> python3 -u skim_tree.py --input nano_9207_cmsDriver.root --output nano_9207.root --config NanoProd/config/skim_uhh.yaml --setup skim --skip-empty --verbose 1
== CMSSW: Traceback (most recent call last):
== CMSSW:   File "/srv/skim_tree.py", line 265, in <module>
== CMSSW:     with open(args.config, 'r') as f:
== CMSSW: FileNotFoundError: [Errno 2] No such file or directory: 'NanoProd/config/skim_uhh.yaml'
== CMSSW: Traceback (most recent call last):
== CMSSW:   File "/srv/crabJob.py", line 121, in processFile
== CMSSW:     jobModule.processFile(module_input_file, output_file, tmp_files, cmssw_report, cmd_line_args, params)
== CMSSW:   File "crabJob_nanoProd.py", line 64, in processFile
== CMSSW:     sh_call(cmd_line, verbose=1)
== CMSSW:   File "/srv/sh_tools.py", line 95, in sh_call
== CMSSW:     raise ShCallError(cmd_str, proc.returncode)
== CMSSW: sh_tools.ShCallError: Error while running "python3 -u skim_tree.py --input nano_9207_cmsDriver.root --output nano_9207.root --config NanoProd/config/skim_uhh.yaml --setup skim --skip-empty --verbose 1." Error code: 1
== CMSSW:
== CMSSW: Failed to process /store/data/Run2018D/EGamma/MINIAOD/UL2018_MiniAODv2_GT36-v2/2560007/8206948F-F793-5647-94D0-1394D05EA180.root
== CMSSW: Traceback (most recent call last):
== CMSSW:   File "/srv/crabJob.py", line 187, in <module>
== CMSSW:     runJob(sys.argv[1:])
== CMSSW:   File "/srv/crabJob.py", line 175, in runJob
== CMSSW:     raise RuntimeError("No output files were produced.")
== CMSSW: RuntimeError: No output files were produced.
== CMSSW:
== CMSSW: Job result: 1
== CMSSW:
== CMSSW:         Scram Command Diagnostic:
== CMSSW:         Command : scramv1
== CMSSW:         Architecture: el8_amd64_gcc11
== CMSSW:         Executed: stdbuf -oL -eL /srv/crabJob.sh  3685  > cmsRun-stdout.log.tmp 2>&1
== CMSSW:         Exit Status: 5
== CMSSW:         Stdout:
== CMSSW:         Stderr: None
======== CMSSW OUTPUT FINSHING ========

```

</details>

As you can see, the miniAOD file is processed but the skim config cannot be found on the remote site. You can find a summary of my setup below this message. As far as I can tell, my configuration file follows the example shown in the [documentation](https://kandrosov.github.io/RunKit/crabOverseer/#main-configuration-file-format). Do you have any suggestions how I can fix this issue?

If you need more information from my side, please don't hesitate to tell me! Thanks a lot in advance for your help.

Cheers,
Philip

<details>
<summary> Setup summary </summary>

# Git setup

- branch: `main`
- commit: a70643a03d0c6d585b6e969ac27508dc6fbf1c89

# Directory tree

Following structure only shows relevant files

```
NanoProd
|
|------RunKit
|------NanoProd
           |
           |------config
                      |
                      |------law.cfg
                      |------skim_htt.cfg
                      |------skim_uhh.yaml
                      |------skim.yaml
           |------crab
                      |------overseer_cfg_uhh.yaml
                      |------Run2_2018_uhh
                                 |
                                 |------resubmit_data2.yaml
           |------python
                      |
                      |------benchmarks.py
                      |------customize.py
                      |------__pycache__
                      |------uhh.py
```

# overseer_cfg_uhh.yaml

<details>
<summary> file content </summary>

```yaml
cmsswPython: RunKit/nanoProdWrapper.py
params:
  customise: NanoProd/NanoProd/customize.customize
  skimCfg: skim_uhh.yaml
  skimSetup: skim
  skimSetupFailed: skim_failed
  maxEvents: -1
splitting: FileBased
unitsPerJob: 2
scriptExe: RunKit/crabJob.sh
outputFiles:
  - nano.root
filesToTransfer:
  - RunKit/crabJob.sh
  - RunKit/crabJob.py
  - RunKit/crabJob_nanoProd.py
  - RunKit/skim_tree.py
  - RunKit/sh_tools.py
  - NanoProd/config/skim_uhh.yaml
  - NanoProd/python/customize.py
site: T2_DE_DESY
crabOutput: /store/user/pkeicher/crab_nano_v12
localCrabOutput: /pnfs/desy.de/cms/tier2/store/user/pkeicher/crab_nano_v12
finalOutput: /pnfs/desy.de/cms/tier2/store/user/pkeicher/crab_nano_v12
maxMemory: 2500
numCores: 1
inputDBS: global
ignoreLocality: False
allowNonValid: False
dryrun: False
maxRecoveryCount: 3
updateInterval: 5
localProcessing:
  lawTask: UHHProdTask
  workflow: htcondor
  bootstrap: bootstrap.sh
#  requirements: ( (OpSysAndVer =?= "CentOS7") || (OpSysAndVer =?= "CentOS8") )
targetOutputFileSize: 2048
renewKerberosTicket: True
whitelistFinalRecovery:
  - T1_DE_KIT
  - T2_CH_CERN
  - T2_DE_DESY
  - T2_IT_Legnaro
```

</details>

# NanoProd/crab/Run2_2018_uhh/resubmit_data2.yaml

<details>
<summary> file content </summary>

```yaml
config:
  params:
    sampleType: data
    era: Run2_2018
    storeFailed: False
  # lumiMask: /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions18/13TeV/Legacy_2018/Cert_314472-325175_13TeV_Legacy2018_Collisions18_JSON.txt
  # recommendations: https://twiki.cern.ch/twiki/bin/view/CMS/PdmVRun2LegacyAnalysis (2023-08-15)


EGamma_Run2018D:
  inputDataset: /EGamma/Run2018D-UL2018_MiniAODv2_GT36-v2/MINIAOD
  sampleType: data
```

</details>

</details>
